post http://localhost:8080/api/user/signup/
Content-Type: application/json

{
    "username": "first_user", 
	"password": "password"
}



# {
# 	"username": "second_user", 
# 	"password": "second_user"
# }

# post http://localhost:8080/api/user/signin/
# Content-Type: application/json

# {
#     "id" : 1,
#     "username": "test", 
# 	"password": "test"
# }
